title: PDF Gallery
email: myzhang1029@hotmail.com
description: >-
  CSC DP2 Project Week Gallery.
baseurl: "/csc_pdf_gallery"
url: "https://myzhang1029.github.io"
github_username:  myzhang1029

# About/contact
author:
  name:              Zhang Maiyun
  url:               https://myzhang1029.github.io
  email:             myzhang1029@hotmail.com

github:
  repo:              https://github.com/myzhang1029/csc_pdf_gallery

theme: minima